---
name: Validate CSS files
on: [push, workflow_dispatch]

jobs:
  csslint:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the code
        uses: actions/checkout@v4.1.0

      - name: Download .stylelintrc
        uses: suisei-cn/actions-download-file@v1.6.0
        with:
          url: "https://raw.githubusercontent.com/fharper/gh-configs/main/.stylelintrc"

      - name: stylelint
        uses: actions-hub/stylelint@v1.1.6
        env:
          PATTERN: "**/*.css"
